//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT
    {
        public string DISTRICT_ID { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string PROVINCE_ID { get; set; }
        public string TYPE { get; set; }
    }
}
