//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    
    public partial class FRONT_SP_SEARCH_Result1
    {
        public int SP_ID { get; set; }
        public string SP_TM_NAME { get; set; }
        public string SP_MERCHANT_NAME { get; set; }
        public Nullable<int> TM_ID { get; set; }
        public string SP_NAME { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string WARD_NAME { get; set; }
        public string SP_ADDRESS { get; set; }
        public string SP_PHONE { get; set; }
        public string SP_WEBSITE { get; set; }
        public string SP_DESCRIPTION { get; set; }
        public string IMAGE_URL { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public Nullable<System.Guid> SP_GUID { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<long> ROWNUMBER { get; set; }
    }
}
