//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    
    public partial class PROC_BANK_SELECTBYID_Result1
    {
        public int BANNER_ID { get; set; }
        public System.Guid BANNER_GUID { get; set; }
        public string BANNER_TITLE { get; set; }
        public string BANNER_DESCRIPTION { get; set; }
        public string BANNER_KEYWORD { get; set; }
        public string IMAGE_URL { get; set; }
        public string LINK { get; set; }
        public string LINK_ANDROID { get; set; }
        public string LINK_IOS { get; set; }
        public string BANNER_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> ORD { get; set; }
        public int RELATION_ID { get; set; }
        public string RELATION_TYPE { get; set; }
        public System.Guid RELATION_DATA_ID { get; set; }
        public System.Guid RELATION_RELATED_ID { get; set; }
        public string RELATION_STATUS { get; set; }
        public int CATE_ID { get; set; }
        public System.Guid CATE_GUID { get; set; }
        public string CATE_NAME { get; set; }
        public string CATE_ALIAS { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string CATE_DESCRIPTION { get; set; }
        public string CATE_KEYWORD { get; set; }
        public string CATE_PERMALINK { get; set; }
        public string CATE_THUMBNAIL { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<byte> CATE_ORD { get; set; }
        public string CATE_CREATEBY { get; set; }
        public Nullable<System.DateTime> CATE_MODIFIEDON { get; set; }
        public string CATE_MODIFIEDBY { get; set; }
        public string CATE_STATUS { get; set; }
        public string PRIORITIZE { get; set; }
    }
}
