//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public int ST_ID { get; set; }
        public string ST_CODE { get; set; }
        public string ST_KEY { get; set; }
        public string ST_VALUE { get; set; }
        public string ST_NOTE { get; set; }
        public string STATUS { get; set; }
    }
}
