//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SP
    {
        public int SP_ID { get; set; }
        public string SP_MERCHANT_NAME { get; set; }
        public string SP_TM_NAME { get; set; }
        public Nullable<int> TM_ID { get; set; }
        public string SP_NAME { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string WARD_NAME { get; set; }
        public string SP_ADDRESS { get; set; }
        public string SP_PHONE { get; set; }
        public string SP_WEBSITE { get; set; }
        public string SP_DESCRIPTION { get; set; }
        public string IMAGE_URL { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public Nullable<System.Guid> SP_GUID { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid RELATION_DATA_ID { get; set; }
        public System.Guid RELATION_RELATED_ID { get; set; }
        public string PG_ID { get; set; }
        public string PG_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.Guid> PG_GUID { get; set; }
        public string RELATION_TYPE { get; set; }
        public string FULL_ADDRESS { get; set; }
    }
}
