//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADE_MARK
    {
        public int TM_ID { get; set; }
        public string TM_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string TM_STATUS { get; set; }
        public string STATUS { get; set; }
        public Nullable<byte> ORD { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
    }
}
