//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADEMART_PROGRAM
    {
        public int ID { get; set; }
        public string PG_ID { get; set; }
        public Nullable<int> TM_ID { get; set; }
        public int TMID { get; set; }
        public string TM_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string TM_STATUS { get; set; }
        public string STATUS { get; set; }
        public Nullable<byte> ORD { get; set; }
    }
}
